openapi: 3.0.1
info:
  title: Nadia's Demo Swagger
  description: This is the swagger file that goes with our server code
  version: 1.0.1
servers:
- url: /api
paths:
  /login:
    post:
      tags:
      - User Authentication
      summary: Account login
      description: User login. Takes in a post request with username/email and password
      operationId: routes.login
      requestBody:
        description: login data
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: its email
                password:
                  type: string
                  description: password
        required: true
      responses:
        200:
          description: OK, JWT login token issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: user access token
        401:
          description: Bad email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: server message
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: server message
  /secret:
    get:
      tags:
        - User Secret
      summary: Return secret string
      operationId: routes.get_secret
      responses:
        '200':
          description: secret response
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: secert message
#      security:
#      - jwt: ['secret']
  /verify:
    get:
      tags:
        - User Authentication
      summary: verify user
      operationId: routes.verify
      responses:
        '200':
          description: verify user
          content:
            'text/plain':
              schema:
                type: boolean
#      security:
#      - jwt: ['secret']
  /info:
    get:
      tags:
        - Open API
      summary: Return system information
      operationId: routes.get_info
      responses:
        '200':
          description: sys info
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                    description: server address
                  date:
                    type: string
                    description: current date
                  hostname:
                    type: string
                    description: server host name
                  time:
                    type: string
                    description: current server time

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
